name: Build Android

on:
  workflow_call:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Version Number
        run: |
          VERSION_NUMBER="${{ inputs.version }}"
          if [[ "$OSTYPE" == "darwin"* ]]; then
          sed -i '' "s/^version: .*/version: $VERSION_NUMBER/" pubspec.yaml
          else
          sed -i "s/^version: .*/version: $VERSION_NUMBER/" pubspec.yaml
          fi
        shell: bash

      - name: Cache Android and Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Android/sdk
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-sdk-flutter-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sdk-flutter-${{ github.ref }}-
            ${{ runner.os }}-sdk-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Run lint
        run: flutter analyze

      - name: Build App bundle
        run: flutter build appbundle

      - name: Build Apk
        run: flutter build apk

      - name: Run tests
        run: flutter test

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload Apk
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

