name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at 00:00 UTC
  workflow_dispatch:


jobs:
  build_android:
    uses: ./.github/workflows/android.yaml
    with:
      version: "1.0.0"

  build_ios:
    uses: ./.github/workflows/ios.yaml
    with:
      version: "1.0.0"


  publish:
    runs-on: ubuntu-latest
    needs: [ build_android,build_ios ]
    steps:
      - uses: actions/checkout@v4

      - name: Download Android App bundle
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk
          path: build

      - name: Download iOS IPA
        uses: actions/download-artifact@v4
        with:
          name: ipa
          path: build

      - name: E2E Tests
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: build/app-release.apk
