name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at 00:00 UTC
  workflow_dispatch:


jobs:
  build_android:
    uses: ./.github/workflows/build_android.yaml
    with:
      version: "1.0.0"

  build_ios:
    uses: ./.github/workflows/build_ios.yaml
    with:
      version: "1.0.0"


  publish:
    runs-on: ubuntu-latest
    needs: [ build_android,build_ios ]
    steps:
      - name: Download Android App bundle
        uses: actions/download-artifact@v3
        with:
          name: app-release.aab
          path: build

      - name: Download iOS IPA
        uses: actions/download-artifact@v3
        with:
          name: Runner.app
          path: build

