name: PR build

on:
  pull_request:
    branches:
      - main

jobs:
  build_android:
    uses: ./.github/workflows/build_android.yaml
    with:
      version: "${{ github.event.pull_request.number }}"

  build_ios:
    uses: ./.github/workflows/build_ios.yaml
    with:
      version: "${{ github.event.pull_request.number }}"