name: PR build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Android, iOS SDK, and Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Android/sdk
            ~/Library/Developer/Xcode
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-sdk-flutter-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sdk-flutter-${{ github.ref }}-
            ${{ runner.os }}-sdk-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Run lint
        run: flutter analyze

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Build APK
        run: flutter build apk

      - name: Run tests
        run: flutter test


  publish:
    runs-on: macos-latest
    needs: build
    steps:

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/iphoneos/Runner.app