name: Release Artifacts

on:
  release:
    types: [created]

jobs:

  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Information
        run: |
          echo "Release Title: ${{ github.event.release.name }}"
          echo "Release Notes: ${{ github.event.release.body }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"


  build_android:
    uses: ./.github/workflows/android.yaml
    with:
      version: ${{ github.event.release.tag_name }}

  build_ios:
    uses: ./.github/workflows/ios.yaml
    with:
      version: ${{ github.event.release.tag_name }}

  publish:
    runs-on: ubuntu-latest
    needs: [ build_android, build_ios ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Android App bundle
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk
          path: build

      - name: Download iOS IPA
        uses: actions/download-artifact@v4
        with:
          name: ipa
          path: build



      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/zip