name: Production Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      version_number:
        description: 'Version number'
        required: true
      release_notes:
        description: 'Release notes'
        required: true
jobs:
  build_android:
    uses: ./.github/workflows/android.yaml
    with:
      version: "${{ github.event.inputs.version_number }}"

  build_ios:
    uses: ./.github/workflows/ios.yaml
    with:
      version: "${{ github.event.inputs.version_number }}"

  publish:
    runs-on: ubuntu-latest
    needs: [ build_android, build_ios ]
    steps:
      - name: Download Android App bundle
        uses: actions/download-artifact@v3
        with:
          name: app-release.aab
          path: build

      - name: Download iOS IPA
        uses: actions/download-artifact@v3
        with:
          name: Runner.app
          path: build

      - name: Publish to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
          packageName: org.github.flutter.gha.flutter_gha
          releaseFiles: app-release.aab
          track: internal
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
#          whatsNewDirectory: distribution/whatsnew
#          mappingFile: app/build/outputs/mapping/release/mapping.txt
#          debugSymbols: app/intermediates/merged_native_libs/release/out/lib